on:
  push:
    branches:
      - main  

name: deploy

jobs:
  deploy:
    name: deploy cloud run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        env:
          PORT: ${{ env.PORT }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "PORT=${PORT}" > .env
          echo "API_KEY=${API_KEY}" >> .env

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.LOGIN }}

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/sebarray/try-action:latest
